//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="WS_TITULOS_CLIENTE.sapiens_Syncnutriplan_cre_titulos")]
    public interface sapiens_Syncnutriplan_cre_titulos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/InserirObsMovimen" +
            "toRequest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/InserirObsMovimen" +
            "toResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoOut InserirObsMovimento(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/InserirObsMovimen" +
            "toRequest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/InserirObsMovimen" +
            "toResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoOut> InserirObsMovimentoAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/AlterarObsTituloR" +
            "equest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/AlterarObsTituloR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloOut AlterarObsTitulo(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/AlterarObsTituloR" +
            "equest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/AlterarObsTituloR" +
            "esponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloOut> AlterarObsTituloAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/RecalcularComissa" +
            "oRequest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/RecalcularComissa" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoOut RecalcularComissao(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/RecalcularComissa" +
            "oRequest", ReplyAction="http://services.senior.com.br/sapiens_Syncnutriplan_cre_titulos/RecalcularComissa" +
            "oResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoOut> RecalcularComissaoAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosInserirObsMovimentoIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCodEmpField;
        
        private string aCodFilField;
        
        private string aCodSnfField;
        
        private string aCodTptField;
        
        private string aFilNfvField;
        
        private string aNumNfvField;
        
        private string aNumTitField;
        
        private string aObsTitField;
        
        private string aTipInsField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACodEmp {
            get {
                return this.aCodEmpField;
            }
            set {
                this.aCodEmpField = value;
                this.RaisePropertyChanged("ACodEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ACodFil {
            get {
                return this.aCodFilField;
            }
            set {
                this.aCodFilField = value;
                this.RaisePropertyChanged("ACodFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ACodSnf {
            get {
                return this.aCodSnfField;
            }
            set {
                this.aCodSnfField = value;
                this.RaisePropertyChanged("ACodSnf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ACodTpt {
            get {
                return this.aCodTptField;
            }
            set {
                this.aCodTptField = value;
                this.RaisePropertyChanged("ACodTpt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string AFilNfv {
            get {
                return this.aFilNfvField;
            }
            set {
                this.aFilNfvField = value;
                this.RaisePropertyChanged("AFilNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string ANumNfv {
            get {
                return this.aNumNfvField;
            }
            set {
                this.aNumNfvField = value;
                this.RaisePropertyChanged("ANumNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ANumTit {
            get {
                return this.aNumTitField;
            }
            set {
                this.aNumTitField = value;
                this.RaisePropertyChanged("ANumTit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string AObsTit {
            get {
                return this.aObsTitField;
            }
            set {
                this.aObsTitField = value;
                this.RaisePropertyChanged("AObsTit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string ATipIns {
            get {
                return this.aTipInsField;
            }
            set {
                this.aTipInsField = value;
                this.RaisePropertyChanged("ATipIns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosRecalcularComissaoOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aMsgRetField;
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string AMsgRet {
            get {
                return this.aMsgRetField;
            }
            set {
                this.aMsgRetField = value;
                this.RaisePropertyChanged("AMsgRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosRecalcularComissaoIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCodSnfField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> nCodEmpField;
        
        private bool nCodEmpFieldSpecified;
        
        private System.Nullable<int> nCodFilField;
        
        private bool nCodFilFieldSpecified;
        
        private System.Nullable<int> nNumNfvField;
        
        private bool nNumNfvFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACodSnf {
            get {
                return this.aCodSnfField;
            }
            set {
                this.aCodSnfField = value;
                this.RaisePropertyChanged("ACodSnf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> NCodEmp {
            get {
                return this.nCodEmpField;
            }
            set {
                this.nCodEmpField = value;
                this.RaisePropertyChanged("NCodEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NCodEmpSpecified {
            get {
                return this.nCodEmpFieldSpecified;
            }
            set {
                this.nCodEmpFieldSpecified = value;
                this.RaisePropertyChanged("NCodEmpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> NCodFil {
            get {
                return this.nCodFilField;
            }
            set {
                this.nCodFilField = value;
                this.RaisePropertyChanged("NCodFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NCodFilSpecified {
            get {
                return this.nCodFilFieldSpecified;
            }
            set {
                this.nCodFilFieldSpecified = value;
                this.RaisePropertyChanged("NCodFilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> NNumNfv {
            get {
                return this.nNumNfvField;
            }
            set {
                this.nNumNfvField = value;
                this.RaisePropertyChanged("NNumNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NNumNfvSpecified {
            get {
                return this.nNumNfvFieldSpecified;
            }
            set {
                this.nNumNfvFieldSpecified = value;
                this.RaisePropertyChanged("NNumNfvSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosAlterarObsTituloOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string mensagemRetornoField;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string tipoRetorno {
            get {
                return this.tipoRetornoField;
            }
            set {
                this.tipoRetornoField = value;
                this.RaisePropertyChanged("tipoRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosAlterarObsTituloIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCodEmpField;
        
        private string aCodFilField;
        
        private string aCodSnfField;
        
        private string aCodTptField;
        
        private string aFilNfvField;
        
        private string aNumNfvField;
        
        private string aNumTitField;
        
        private string aObsTcrField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACodEmp {
            get {
                return this.aCodEmpField;
            }
            set {
                this.aCodEmpField = value;
                this.RaisePropertyChanged("ACodEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ACodFil {
            get {
                return this.aCodFilField;
            }
            set {
                this.aCodFilField = value;
                this.RaisePropertyChanged("ACodFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ACodSnf {
            get {
                return this.aCodSnfField;
            }
            set {
                this.aCodSnfField = value;
                this.RaisePropertyChanged("ACodSnf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ACodTpt {
            get {
                return this.aCodTptField;
            }
            set {
                this.aCodTptField = value;
                this.RaisePropertyChanged("ACodTpt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string AFilNfv {
            get {
                return this.aFilNfvField;
            }
            set {
                this.aFilNfvField = value;
                this.RaisePropertyChanged("AFilNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string ANumNfv {
            get {
                return this.aNumNfvField;
            }
            set {
                this.aNumNfvField = value;
                this.RaisePropertyChanged("ANumNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ANumTit {
            get {
                return this.aNumTitField;
            }
            set {
                this.aNumTitField = value;
                this.RaisePropertyChanged("ANumTit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string AObsTcr {
            get {
                return this.aObsTcrField;
            }
            set {
                this.aObsTcrField = value;
                this.RaisePropertyChanged("AObsTcr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class titulosInserirObsMovimentoOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string mensagemRetornoField;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string tipoRetorno {
            get {
                return this.tipoRetornoField;
            }
            set {
                this.tipoRetornoField = value;
                this.RaisePropertyChanged("tipoRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sapiens_Syncnutriplan_cre_titulosChannel : NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.sapiens_Syncnutriplan_cre_titulos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sapiens_Syncnutriplan_cre_titulosClient : System.ServiceModel.ClientBase<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.sapiens_Syncnutriplan_cre_titulos>, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.sapiens_Syncnutriplan_cre_titulos {
        
        public sapiens_Syncnutriplan_cre_titulosClient() {
        }
        
        public sapiens_Syncnutriplan_cre_titulosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sapiens_Syncnutriplan_cre_titulosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Syncnutriplan_cre_titulosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Syncnutriplan_cre_titulosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoOut InserirObsMovimento(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoIn parameters) {
            return base.Channel.InserirObsMovimento(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoOut> InserirObsMovimentoAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosInserirObsMovimentoIn parameters) {
            return base.Channel.InserirObsMovimentoAsync(user, password, encryption, parameters);
        }
        
        public NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloOut AlterarObsTitulo(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloIn parameters) {
            return base.Channel.AlterarObsTitulo(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloOut> AlterarObsTituloAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosAlterarObsTituloIn parameters) {
            return base.Channel.AlterarObsTituloAsync(user, password, encryption, parameters);
        }
        
        public NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoOut RecalcularComissao(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoIn parameters) {
            return base.Channel.RecalcularComissao(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoOut> RecalcularComissaoAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_TITULOS_CLIENTE.titulosRecalcularComissaoIn parameters) {
            return base.Channel.RecalcularComissaoAsync(user, password, encryption, parameters);
        }
    }
}
