//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="WS_NOTAS.sapiens_Syncnutriplan_nfv_notafiscal")]
    public interface sapiens_Syncnutriplan_nfv_notafiscal {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesOut IncluirObservacoes(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesOut> IncluirObservacoesAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class notafiscalIncluirObservacoesIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aCodEmpField;
        
        private string aCodFilField;
        
        private string aCodSnfField;
        
        private string aNumNfvField;
        
        private string aObsNfvField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ACodEmp {
            get {
                return this.aCodEmpField;
            }
            set {
                this.aCodEmpField = value;
                this.RaisePropertyChanged("ACodEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ACodFil {
            get {
                return this.aCodFilField;
            }
            set {
                this.aCodFilField = value;
                this.RaisePropertyChanged("ACodFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ACodSnf {
            get {
                return this.aCodSnfField;
            }
            set {
                this.aCodSnfField = value;
                this.RaisePropertyChanged("ACodSnf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ANumNfv {
            get {
                return this.aNumNfvField;
            }
            set {
                this.aNumNfvField = value;
                this.RaisePropertyChanged("ANumNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string AObsNfv {
            get {
                return this.aObsNfvField;
            }
            set {
                this.aObsNfvField = value;
                this.RaisePropertyChanged("AObsNfv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class notafiscalIncluirObservacoesOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string mensagemRetornoField;
        
        private string tipoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
                this.RaisePropertyChanged("mensagemRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string tipoRetorno {
            get {
                return this.tipoRetornoField;
            }
            set {
                this.tipoRetornoField = value;
                this.RaisePropertyChanged("tipoRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sapiens_Syncnutriplan_nfv_notafiscalChannel : NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.sapiens_Syncnutriplan_nfv_notafiscal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sapiens_Syncnutriplan_nfv_notafiscalClient : System.ServiceModel.ClientBase<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.sapiens_Syncnutriplan_nfv_notafiscal>, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.sapiens_Syncnutriplan_nfv_notafiscal {
        
        public sapiens_Syncnutriplan_nfv_notafiscalClient() {
        }
        
        public sapiens_Syncnutriplan_nfv_notafiscalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sapiens_Syncnutriplan_nfv_notafiscalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Syncnutriplan_nfv_notafiscalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Syncnutriplan_nfv_notafiscalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesOut IncluirObservacoes(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesIn parameters) {
            return base.Channel.IncluirObservacoes(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesOut> IncluirObservacoesAsync(string user, string password, int encryption, NUTRIPLAN_WEB.MVC_4_BS.DataAccess.WS_NOTAS.notafiscalIncluirObservacoesIn parameters) {
            return base.Channel.IncluirObservacoesAsync(user, password, encryption, parameters);
        }
    }
}
